### ISSUE TITLE
What value is expected for mandatory field 'location'?

### ISSUE THREAD

**Issue by jukey** [imoutits/PokeIV#19]
The last version of PokeIV requires some value for location.

What values are valid here?
- Lat/Lon comibantions or something like 
- de-DE or 
- the name of the next City?

I fear to enter something that comes to my mind as it should fit the behaviour of the app.

**Comment by canele** [comment]
lat/long or location name. The name can be anything understood by google's geolocator (city, district, zip, etc.)
