### ISSUE TITLE
[Request] Using different names for the pokemon

### ISSUE THREAD

**Issue by Darkztar** [imoutits/PokeIV#4]
I've created a "names.tsv" in the same format, but with the german names of the pokemon in the .\dist folder (I'm using the GUI version) to rename my pokemon back with {-}{pokemon} to the german names, but it didn't work, it still used the english names.

Is it possible to do this somehow or would it be a new feature?

Then it would be great if this would be possible :)

**Comment by canele** [comment]
I stopped using the names.tsv file recently in favour of a JSON one with more information (that I may eventually want to use) that was included in the pgoapi. It's located in the dist/pgoapi folder (pokemon.json).

~~If you make a new version of the file with the german names and submit a pull request I could add a language option to the program.~~

Actually, just submit the german names.tsv you made and I'll use that. The other information in the pokemon.json would just be duplicated.

**Comment by Darkztar** [comment]
For some reason I couldn't upload the zip here :/

So here the dropbox link, where I uploaded it: https://goo.gl/Hu7120

**Comment by dontmesswithfreitag** [comment]
Well some custom renaming would be fine. Can't figure out how to rename pokemons like
"xlax"{iv.2}"_LB"

**Comment by canele** [comment]
Added the german names option: -l german (can be added similarly to config: "languge", "german".

You can also now rename pokemon with custom static strings: {-}{"IV"}{iv.2} => IV-(iv)
